CREATE DATABASE LAPTOP;
USE LAPTOP ;
CREATE TABLE LAPTOP_INFO (
    id INTEGER PRIMARY KEY,
    brand_name VARCHAR(20) NOT NULL UNIQUE,
    model_name VARCHAR(20) NOT NULL UNIQUE,
    warranty int  ,
    price REAL NOT NULL

);

CREATE TABLE MOBILE_INFO (
    id INTEGER PRIMARY KEY,
    brand_name VARCHAR(20) NOT NULL UNIQUE,
    model_name VARCHAR(20) NOT NULL UNIQUE,
    warranty int,
    manufacturing_year int, 
    offer VARCHAR(20) NOT NULL UNIQUE,
    price REAL NOT NULL
);

CREATE TABLE washing_machine (
    id INTEGER PRIMARY KEY,
    brand VARCHAR(30) NOT NULL UNIQUE,
    model VARCHAR(30) NOT NULL UNIQUE,
    capacity INTEGER NOT NULL,
    price REAL NOT NULL,
    color VARCHAR(10) NOT NULL 
		
);



INSERT INTO LAPTOP_INFO VALUES (1,"SAMSUNG",2013,2,55000);
INSERT INTO MOBILE_INFO VALUES (2,"ONEPLUS",2024,5,2024,"FIFTY PERCENT", 75000);
INSERT INTO washing_machine VALUES (3,"Samsung",2014,4,22000,"White");


ALTER TABLE LAPTOP_INFO  ADD warranty int NOT NULL UNIQUE;
ALTER TABLE MOBILE_INFO  ADD offer VARCHAR(20) NOT NULL UNIQUE;
ALTER TABLE washing_machine ADD COLUMN color VARCHAR(10) NOT NULL;


SELECT * FROM LAPTOP_INFO , MOBILE_INFO ,washing_machine




